// AUTO-GENERATED by `bun run sync-tui` — do not edit by hand.
// Re-run the sync after the Noetic CLI changes the surface this file describes.

// Captured: 2026-04-30T19:48:21.880Z
// CLI commit: b46954c

export interface PowerlineSegment {
  glyph: string;
  text: string;
  role: 'agent' | 'model' | 'cwd' | 'branch' | 'tokens' | 'percent' | 'unknown';
}

export interface ContextRow {
  label: string;
  tokens: string;
  pct: number;
  color: 'magenta' | 'blue' | 'cyan' | 'green';
}

export interface HeroChrome {
  powerline: ReadonlyArray<PowerlineSegment>;
  promptPlaceholder: string;
  modeLabel: string;
  modelId: string;
}

export interface ContextSnapshot {
  modelId: string;
  totalUsed: string;
  totalLimit: string;
  totalPct: number;
  overviewRows: ReadonlyArray<ContextRow>;
  layerIds: ReadonlyArray<string>;
}

export const HERO_CHROME: HeroChrome = {
  "powerline": [
    {
      "glyph": "N",
      "text": "",
      "role": "agent"
    },
    {
      "glyph": "*",
      "text": "claude-sonnet-4",
      "role": "model"
    },
    {
      "glyph": "~",
      "text": "~/my-project",
      "role": "cwd"
    },
    {
      "glyph": "±",
      "text": "main*",
      "role": "branch"
    }
  ],
  "promptPlaceholder": "Type a message...",
  "modeLabel": "ACT",
  "modelId": "anthropic/claude-sonnet-4"
} as const;

export const CONTEXT_SNAPSHOT: ContextSnapshot = {
  "modelId": "anthropic/claude-sonnet-4",
  "totalUsed": "21.8k",
  "totalLimit": "200.0k",
  "totalPct": 10.9,
  "overviewRows": [
    {
      "label": "System prompt",
      "tokens": "2.8k",
      "pct": 1.4,
      "color": "magenta"
    },
    {
      "label": "Tools",
      "tokens": "12.9k",
      "pct": 6.5,
      "color": "blue"
    },
    {
      "label": "agent-md",
      "tokens": "5.3k",
      "pct": 2.6,
      "color": "cyan"
    },
    {
      "label": "durable-task-state",
      "tokens": "20",
      "pct": 0,
      "color": "cyan"
    },
    {
      "label": "file-reference",
      "tokens": "0",
      "pct": 0,
      "color": "cyan"
    },
    {
      "label": "reminder",
      "tokens": "42",
      "pct": 0,
      "color": "cyan"
    },
    {
      "label": "skills-memory",
      "tokens": "532",
      "pct": 0.3,
      "color": "cyan"
    },
    {
      "label": "Messages",
      "tokens": "118",
      "pct": 0.1,
      "color": "green"
    }
  ],
  "layerIds": [
    "agent-md",
    "durable-task-state",
    "file-reference",
    "reminder",
    "skills-memory"
  ]
} as const;

// AUTO-GENERATED — re-run 'bun run sync-tui' to refresh.
