import { describe, expect, test } from 'bun:test';
import { z } from 'zod';
import { createLibrary, defineComponent, parseDocument, validateDocument } from '../src';
import { testLibrary } from './_helpers';

describe('createLibrary', () => {
  test('rejects duplicate component names', () => {
    expect(() =>
      createLibrary([
        defineComponent({
          name: 'Card',
        }),
        defineComponent({
          name: 'Card',
        }),
      ]),
    ).toThrow(/duplicate component name 'Card'/);
  });

  test('systemPrompt lists every component with its props and description', () => {
    // The prompt text is generated by @openuidev/lang-core, so assertions are
    // structural (names and props present), not pinned to upstream wording.
    const prompt = testLibrary().systemPrompt();
    for (const token of [
      'Card(',
      'title',
      'A titled container',
      'Progress(',
      'pct',
      'Text(',
      'Stack(',
    ]) {
      expect(prompt).toContain(token);
    }
  });

  test('systemPrompt teaches the full interactive language by default', () => {
    // Regression guard for the options-plumbing gap: the default prompt must
    // cover $state bindings, Query/Mutation, and the Action step vocabulary.
    const prompt = testLibrary().systemPrompt();
    for (const token of [
      '$',
      'Query(',
      'Mutation(',
      'Action([',
      '@Run',
      '@Set',
      '@ToAssistant',
    ]) {
      expect(prompt).toContain(token);
    }
  });

  test('systemPrompt names a real registered component as root', () => {
    // testLibrary sets root: 'Stack'; the prompt must never instruct the
    // model to call a component that does not exist (the `Root` placeholder).
    const prompt = testLibrary().systemPrompt();
    expect(prompt).toContain('root = Stack(');
    expect(prompt).not.toContain('root = Root(');
  });

  test('systemPrompt threads caller PromptOptions through to lang-core', () => {
    const withTools = testLibrary().systemPrompt({
      tools: [
        'sales_tool',
      ],
      additionalRules: [
        'CUSTOM RULE MARKER',
      ],
    });
    expect(withTools).toContain('sales_tool');
    expect(withTools).toContain('CUSTOM RULE MARKER');
    // caller rules extend the defaults, they do not replace them
    expect(withTools).toContain('@ToAssistant');
  });
});

describe('validateDocument', () => {
  const lib = testLibrary();

  test('accepts a valid document including builtins and nested calls', () => {
    const doc = parseDocument(
      [
        '$tab = "a"',
        'sales = Query("sales_tool", {})',
        'root = Stack([Card("Title", [Text("hi")]), Action([@Run(sales)])])',
      ].join('\n'),
    );
    expect(validateDocument(lib, doc)).toEqual([]);
  });

  test('flags unknown components, including nested ones', () => {
    const doc = parseDocument('root = Stack([Sparkline([1, 2])])');
    const issues = validateDocument(lib, doc);
    expect(issues).toHaveLength(1);
    expect(issues[0]?.component).toBe('Sparkline');
    expect(issues[0]?.ref).toBe('root');
  });

  test('flags arity overflow', () => {
    const doc = parseDocument('root = Text("a", "b")');
    const issues = validateDocument(lib, doc);
    expect(issues.some((i) => i.message.includes('too many arguments'))).toBe(true);
  });

  test('flags missing required props', () => {
    const issues = validateDocument(lib, parseDocument('root = Card()'));
    expect(issues).toHaveLength(1);
    expect(issues[0]?.message).toContain("'title'");
  });

  test('literal prop boundaries: 0 and 100 pass, 101 fails, refs skipped', () => {
    expect(validateDocument(lib, parseDocument('root = Progress(0)'))).toEqual([]);
    expect(validateDocument(lib, parseDocument('root = Progress(100)'))).toEqual([]);
    const over = validateDocument(lib, parseDocument('root = Progress(101)'));
    expect(over).toHaveLength(1);
    expect(over[0]?.message).toContain("prop 'pct'");
    // dynamic arg — statically unverifiable, must not be flagged
    expect(validateDocument(lib, parseDocument('root = Progress($pct)'))).toEqual([]);
  });

  test('statements not reachable from root are still validated', () => {
    // Regression guard: lang-core only reports errors for the entry tree, so
    // orphan statements get their own resolution pass.
    const issues = validateDocument(
      lib,
      parseDocument(
        [
          'root = Card("ok")',
          'lost = Bogus("x")',
          'orphan = Progress("not a number")',
        ].join('\n'),
      ),
    );
    expect(issues).toHaveLength(2);
    expect(issues.find((i) => i.ref === 'lost')?.message).toContain("unknown component 'Bogus'");
    expect(issues.find((i) => i.ref === 'orphan')?.message).toContain("prop 'pct'");
  });

  test('documents without a root statement are still validated', () => {
    // A partial re-render turn often re-assigns one statement and never
    // assigns `root`; its components must still be checked.
    const issues = validateDocument(lib, parseDocument('c2 = Progress(101)'));
    expect(issues).toHaveLength(1);
    expect(issues[0]?.ref).toBe('c2');
  });

  test('cross-turn references are never flagged', () => {
    // `chart` and `titleFromLastTurn` live on the merged surface, not in this
    // turn's document; unresolved refs must not produce issues.
    expect(validateDocument(lib, parseDocument('root = Stack([chart])'))).toEqual([]);
    expect(validateDocument(lib, parseDocument('card = Card(titleFromLastTurn)'))).toEqual([]);
  });

  test('a literal object prop containing a `k` key is data, not an AST node', () => {
    const doc = parseDocument('root = Card("T", [{k: 1, label: "x"}])');
    expect(validateDocument(lib, doc)).toEqual([]);
  });

  test('exotic prop schemas degrade to "any" in the prompt', () => {
    const lib2 = createLibrary([
      defineComponent({
        name: 'Odd',
        props: z.object({
          fn: z.custom<() => void>((v) => typeof v === 'function'),
        }),
      }),
    ]);
    // A custom() schema has no JSON-schema type — it degrades to `any`.
    const prompt = lib2.systemPrompt();
    expect(prompt).toContain('Odd(');
    expect(prompt).toContain('fn');
    expect(prompt).toContain('any');
  });
});
